AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM User and Policy for DC Tech Events - AWS Places API v2'

Resources:
  # IAM User for DC Tech Events Places API
  PlacesAPIUser:
    Type: AWS::IAM::User
    Properties:
      UserName: dctech-events-places-api
      Tags:
        - Key: Application
          Value: dctech.events
        - Key: Purpose
          Value: Places API v2 Geocoding

  # IAM Policy for Places API v2
  PlacesAPIPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: dctech-events-places-api-policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowPlacesAPIv2Geocoding
            Effect: Allow
            Action:
              - geo-places:SearchText
              - geo-places:Geocode
              - geo-places:ReverseGeocode
              - geo-places:GetPlace
            Resource: '*'
      Users:
        - !Ref PlacesAPIUser

  # Access Key for the User
  PlacesAPIAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref PlacesAPIUser

Outputs:
  UserName:
    Description: IAM User Name for Places API v2
    Value: !Ref PlacesAPIUser
    Export:
      Name: !Sub '${AWS::StackName}-UserName'

  AccessKeyId:
    Description: Access Key ID (Store in GitHub Secrets as AWS_ACCESS_KEY_ID)
    Value: !Ref PlacesAPIAccessKey

  SecretAccessKey:
    Description: Secret Access Key (Store in GitHub Secrets as AWS_SECRET_ACCESS_KEY)
    Value: !GetAtt PlacesAPIAccessKey.SecretAccessKey

  PolicyArn:
    Description: ARN of the IAM Policy
    Value: !Ref PlacesAPIPolicy
